### ISSUE TITLE
Class inheritance broken - cannot read property discriminator of undefined

### ISSUE THREAD

**Issue by glmdev** [Omninox/SchematicClass#7]
**Describe the bug**
When trying to call `createModel` on a class which inherits from another class, the function errors out with the message "Cannot read property 'discriminator' or undefined."

```
TypeError: Cannot read property 'discriminator' of undefined
    at createModel (/tmp/sctest/node_modules/mongo-schematic-class/index.js:90:46)
    at Object.<anonymous> (/tmp/sctest/index.js:26:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

**MCVE (Minimal Complete and Verifiable Example)**
```javascript
class Model {

}

class Parent extends Model {
	static get __context() {
		return {
			name: String,
		}
	}

	hello() {
		console.log(this.name)
	}
}

class Child extends Parent {
	static get __context() {
		return {...super.__context, ...{
			type: String,
		}}
	}
}

const { createModel } = require('mongo-schematic-class')
createModel(Child)
```

**Expected behavior**
A Mongo model will be created from `Child` with the name and type properties, and the `hello` method.

**Versions (please complete the following information):**
 - MongoDB: N/A - tested with none instantiated
 - mongoose: N/A - tested with non instantiated
 - mongo-schematic-class: 1.0.3

**Additional Checks**
 - [X] I am sure the issue does not exist in mongoose.
 - [x] I have the most recent version of mongo-schematic-class

**Additional context**

**Comment by glmdev** [comment]
Ah, I see now that I need to call createModel on the parent class first, but is it possible to avoid this?

**Comment by c1moore** [comment]
I'm open to feedback on this one.  This was a design choice based on a common pattern I've used when building mongoose apps where you define each model/class in a separate file.  So it ends up looking something like this:

**model.js**
```js
const { createModel } = require('mongo-schematic-class');

class Model {

}

module.exports = createModel(Model);
```

**parent.js**
```js
const { createModel } = require('mongo-schematic-class');
const Model = require('./model');

class Parent extends Model.__class {
	static get __context() {
		return {
			name: String,
		}
	}

	hello() {
		console.log(this.name)
	}
}

module.exports = createModel(Parent);
```

If you follow this pattern, you can add more and more subclasses to Model over time.  You can also take advantage of the normal benefits of using mongoose discriminators from other application code (e.g. querying for any "Model" whether it be a "Parent", "Child", or "Parent2").

**Comment by c1moore** [comment]
That being said, the error message should be improved.

**Comment by c1moore** [comment]
I'm going to close this issue.  Feel free to reopen it if you would like to continue the discussion.
